---
tokenizers:
  - 'BPE'
  - 'UNI'
  - 'WPC'

vocab_size:
  - 1000
  - 5000
  - 10000
  - 20000
  - 30000
  - 40000
  - 50000
  - 60000
  - 70000

language:
  - "en"
  - "nl"
  - "es"
  - "fr"

traindir: "../data/train/"
evaldir: "../data/eval/"
outdir: "../results/"
